version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/ruby:3.1.2
    working_directory: ~/app

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      
      # キャッシュを復元 (GemとNodeモジュール)
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - yarn-cache-{{ checksum "yarn.lock" }}

      # 必要な依存関係のインストール
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y build-essential libpq-dev curl nodejs yarn
            bundle install --path vendor/bundle
            yarn install

      # キャッシュを保存
      - save_cache:
          paths:
            - vendor/bundle
            - node_modules
          key: dependency-cache-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

      # Rails アセットのプリコンパイル
      - run:
          name: Precompile Rails assets
          command: |
            RAILS_ENV=production SECRET_KEY_BASE=dummyvalue bundle exec rails assets:precompile

  deploy:
    executor: docker-executor
    steps:
      - checkout

      # 環境変数の設定
      - run:
          name: Set environment variables
          command: |
            echo 'export HEROKU_API_KEY=$HEROKU_API_KEY' >> $BASH_ENV
            echo 'export STRIPE_API_KEY=$STRIPE_API_KEY' >> $BASH_ENV
            source $BASH_ENV

      # Heroku CLI のインストール
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh

      # Heroku への Docker イメージのデプロイ
      - run:
          name: Deploy to Heroku
          command: |
            heroku container:login
            heroku container:push web --app $HEROKU_APP_NAME
            heroku container:release web --app $HEROKU_APP_NAME

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
